### ISSUE TITLE
Collect language from fileNamePatterns to enable inlayhint and find usages

### ISSUE THREAD

**Issue by rcjsuen** [redhat-developer/lsp4ij#1023]
**Version:** 0.13.0-20250506-071038

1. Create the three following files in the same folder.
2. Create a file named `Dockerfile`.
```Dockerfile
ARG VAR=value
FROM scratch
```
3. Create a file name `docker-bake.hcl`.
```HCL
target "foo" {
  dockerfile = "Dockerfile"
  args = {
    VAR = "value2"
  }
}
```
4. Create a file named `compose.yaml`.
```YAML
services:
  test:
    image: alpine
    hostname: h1
  test3:
    hostname: h2
    extends:
      service: test
```
5. Setup the [Docker Language Server](https://github.com/redhat-developer/lsp4ij/blob/bf00081cc95588ea4c4f17a9f5880b4ecf795119/docs/user-defined-ls/docker-language-server.md).
6. Open all three files.
7. Observe that a `textDocument/inlayHints` request is sent for only two of the three files.

Why isn't a request being sent for `compose.yaml`? 🤔
