### ISSUE TITLE
deprecated diagnostics don't work

### ISSUE THREAD

**Issue by DetachHead** [redhat-developer/lsp4ij#431]
according to #358, deprecated diagnostics were added in 0.0.2, but they don't seem to work.

```toml
# pyproject.toml

[tool.basedpyright]
pythonPlatform = "All"
pythonVersion = "3.12"
deprecateTypingAliases = true
```
```py
from typing import Iterable
```

pycharm with the lsp4ij plugin:
![image](https://github.com/user-attachments/assets/65734493-c074-49ef-af72-afca2d44b787)

vscode:
![image](https://github.com/user-attachments/assets/2939e954-2080-45dc-b14f-d7ec46947b74)
